sudo: required
dist: trusty

language: c++

matrix:
    include:
      - compiler: gcc
      - compiler: gcc
        env:
            - 'COMPILE_FLAGS="--std=c++11"'
addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

script:
    - 'echo using gcc : : g++ ${COMPILE_FLAGS} ; > ~/user-config.jam'
    - touch Jamroot.jam
    - cd test && echo bjam include=${TRAVIS_BUILD_DIR}/include
