sudo: required
dist: trusty

language: c++

matrix:
    include:
      - compiler: gcc
        env:
            - 'JAM_TOOLSET=using gcc : : g++ ;'
      - compiler: gcc
        env:
            - 'JAM_TOOLSET=using gcc : : g++ --std=c++11 ;'
addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

script:
    - echo $JAM_TOOLSET > ~/user-config.jam
    - touch Jamroot.jam
    - cd test && bjam include=${TRAVIS_BUILD_DIR}/include
