# Copyright (C) 2005-2008 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Very simple test runner using Ubuntu's copy of Boost, rather than downloading
# our own copy.

# Use Trusty to get a recent version of Boost.
sudo: required
dist: trusty

language: c++

# Install Boost
addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

# Test using default GCC + default GCC in C++11 mode.
# Note: To use other compilers will need to tweak user-config.jam below.
matrix:
    include:
      - compiler: gcc
      - compiler: gcc
        env:
            - COMPILE_FLAGS="--std=c++11"

# Run the tests.
script:
    - 'echo "using gcc : : g++ ${COMPILE_FLAGS} ;" > ~/user-config.jam'
    - cat ~/user-config.jam
    - touch Jamroot.jam
    - cd test && bjam include=${TRAVIS_BUILD_DIR}/include
