sudo: required
dist: trusty

language: c++

matrix:
    include:
      - compiler: gcc
        env:
            - 'JAM_TOOLSET=echo "using gcc : : g++ ;" > ~/user-config.jam'
      - compiler: gcc
        env:
            - 'JAM_TOOLSET=echo "using gcc : : g++ --std=c++11 ;" > ~/user-config.jam'
addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

env:
    - BOOST_BUILD_PATH=/usr/share/boost-build/

script:
    - echo $JAM_TOOLSET > ~/user-config.jam
    - touch Jamroot.jam
    - cd test && bjam include=${TRAVIS_BUILD_DIR}/include
