# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-tools-dev
            - libxml2-utils
            - g++-multilib

matrix:
    include:
      - compiler: gcc
        env: |
            label="gcc C++03";
            user_config="using gcc : : g++-4.8 -fsanitize=address -Werror --std=c++03 ;"
      - compiler: gcc
        env: |
            label="gcc C++11";
            user_config="using gcc : : g++-4.8 -fsanitize=address -Werror --std=c++11 ;"
      - compiler: gcc
        env: |
            label="gcc 32 bit C++11";
            user_config="using gcc : : g++-4.8 -m32 -fsanitize=address -Werror --std=c++11 ;"
      - compiler: clang
        env: |
            label="clang C++11";
            user_config="using clang : : clang++ -fsanitize=address -Werror --std=c++11 ;"
        # sanitized=address not available for 32-bit clang on travis.
      - compiler: clang
        env: |
            label="clang 32 bit";
            user_config="using clang : : clang++ -m32 -Werror --std=c++03 ;"
      - compiler: gcc
        env: |
            label="gcc C++03 interopable1";
            user_config="using gcc : : g++-4.8 -fsanitize=address -Werror --std=c++03 -DBOOST_UNORDERED_INTEROPERABLE_NODES=1 ;"
      - compiler: clang
        env: |
            label="gcc C++11 interopable1";
            user_config="using clang : : clang++ -fsanitize=address -Werror --std=c++03 -DBOOST_UNORDERED_INTEROPERABLE_NODES=1 ;"

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - touch Jamroot.jam
    - cd $HOME
    - echo $user_config > ~/user-config.jam
    - cat ~/user-config.jam
    - wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.bz2
    - tar -xjf boost.tar.bz2
    - mv boost_1_63_0 boost
    - rm -r boost/boost/unordered

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q include=${HOME}/boost include=${TRAVIS_BUILD_DIR}/include
    - xmllint --noout ${TRAVIS_BUILD_DIR}/doc/ref.xml
