sudo: required
dist: trusty

matrix:
    include:
      - compiler: gcc
        install:
          - echo "using gcc ;" > ~/user-config.jam
      - compiler: gcc
        install:
          - echo "using gcc : : g++ --std=c++11 ;" > ~/user-config.jam
addons:
    apt:
        packages:
            - libboost-dev
            - libboost-tools-dev

env:
    - BOOST_BUILD_PATH=/usr/share/boost-build/

script:
    - touch Jamroot.jam
    - cd test && bjam include=${TRAVIS_BUILD_DIR}/include
