# Copyright (C) 2016 Daniel James.
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

# Use Trusty to get a reasonably recent version of Boost.
sudo: required
dist: trusty

language: c++

addons:
    apt:
        packages:
            - libboost-tools-dev
            - libxml2-utils
            - g++-multilib

matrix:
    include:
      - compiler: gcc
        env: |
            label="gcc C++03";
            user_config="using gcc : : g++-4.8 --coverage -fsanitize=address -Werror --std=c++03 ;"
            enable_coverage=1

before_install:
    - if [ -n $enable_coverage ]; then pip install --user cpp-coveralls; fi

before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - touch Jamroot.jam
    - cd $HOME
    - echo $user_config > ~/user-config.jam
    - cat ~/user-config.jam
    - wget -O boost.tar.bz2 https://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.bz2
    - tar -xjf boost.tar.bz2
    - mv boost_1_64_0 boost
    - rm -r boost/boost/unordered

after_success:
    if [ -n $enable_coverage ]; then coveralls -r ${TRAVIS_BUILD_DIR}/bin -b ${TRAVIS_BUILD_DIR}/test ; fi

script:
    - cd ${TRAVIS_BUILD_DIR}/test
    - bjam -q compile_map include=${HOME}/boost include=${TRAVIS_BUILD_DIR}/include
    - xmllint --noout ${TRAVIS_BUILD_DIR}/doc/ref.xml
